Document: absl
Title: Debian absl Manual
Author: <insert document author here>
Abstract: This manual describes what absl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/absl/absl.sgml.gz

Format: postscript
Files: /usr/share/doc/absl/absl.ps.gz

Format: text
Files: /usr/share/doc/absl/absl.text.gz

Format: HTML
Index: /usr/share/doc/absl/html/index.html
Files: /usr/share/doc/absl/html/*.html
